### ISSUE TITLE
Cant run bot

### ISSUE THREAD

**Issue by TylerNe** [ConnorSwis/casino-bot#3]
hi, i got this Issues when run the bot
![image](https://user-images.githubusercontent.com/91006119/153177881-b4be32a8-7ff1-4f34-8e18-2e30536bf9a1.png)

**Comment by leopotty** [comment]
You muss open the Terminal and type "  pip install pyyaml " Hope that helps :D

**Comment by elrubenhd** [comment]
hice todos los pasos y me sale desconectado
